CREATE TABLE "GCG_3537_DAILY_ORD"(
 "BIRUNID" BIGINT,
 "PRODUCT_LINE" VARCHAR(2),
 "PRODUCT_LINE_DESC" VARCHAR(10),
 "PRIOR" DOUBLE,
 "CURRENT_EXT" DOUBLE,
 "HIST" DOUBLE,
 "DATE_ORDER" DATE,
 "TYPE" VARCHAR(1));
